---
--- Atlas-TW English Localization File
--- Simple localization system based on metatables
--- Provides automatic fallback to key names when translations are missing
---
--- Features:
--- - Automatic fallback to key names for missing translations
--- - Metatable-based translation system
--- - Complete English localization strings for Atlas-TW addon
--- - Zone names, instance data, and UI text translations
---
--- @compatible World of Warcraft 1.12
---
AtlasTW.Local = {
    Translations = {},
    __index = function(t, key)
        local value = rawget(t.Translations, key)
        if value == true or value == nil then
            return key
        else
            return value
        end
    end
}

setmetatable(AtlasTW.Local, AtlasTW.Local)

AtlasTWSortIgnore = {"the (.+)"}

---
--- Key binding definitions for Atlas-TW addon
---
BINDING_HEADER_ATLASTW_TITLE = "Atlas-TW Bindings"
BINDING_NAME_ATLASTW_TOGGLE = "Toggle Atlas-TW"
BINDING_NAME_ATLASTW_OPTIONS = "Toggle Options"
BINDING_HEADER_ATLASTWLOOT_TITLE = "AtlasTW Loot Bindings"
BINDING_NAME_ATLASTWLOOT_QL1 = "QuickLook 1"
BINDING_NAME_ATLASTWLOOT_QL2 = "QuickLook 2"
BINDING_NAME_ATLASTWLOOT_QL3 = "QuickLook 3"
BINDING_NAME_ATLASTWLOOT_QL4 = "QuickLook 4"
BINDING_NAME_ATLASTWLOOT_QL5 = "QuickLook 5"
BINDING_NAME_ATLASTWLOOT_QL6 = "QuickLook 6"
BINDING_NAME_ATLASTWLOOT_WISHLIST = "WishList"

AtlasTWZoneSubstitutions = {
	["The Temple of Atal'Hakkar"] = "Sunken Temple"
}

---
--- Translation table containing all localized strings
--- Uses English as the base language with fallback support
---
AtlasTW.Local.Translations = {

	--************************************************
	-- Zone Names, Acronyms, and Common Strings
	--************************************************
	--Colors
	["Blue"] = true,
	["Purple"] = true,
	["Red"] = true,
	["Orange"] = true,
	["White"] = true,
	--Mobs types
	["Boss"] = true,
	["Rare"] = true,
	["Bat"] = true,
	["Snake"] = true,
	["Raptor"] = true,
	["Spider"] = true,
	["Tiger"] = true,
	["Panther"] = true,
	["Pet"] = true,
	["Engineer"] = true,

	--Magic types
	["Fire"] = true,
	["Nature"] = true,
	["Frost"] = true,
	["Shadow"] = true,
	["Arcane"] = true,
	["Physical"] = true,

	--Events
	["Hallow's End"] = true,
	["Scourge Invasion"] = true,
	["Lunar Festival"] = true,

	--Other

	["Show the Quest Panel with AtlasTW"] = true,
	["Show Quest Panel on the Left"] = true,
	["Show Quest Panel on the Right"] = true,
	["Color Quests by Level"] = true,
	["Color Quests from the Questlog"] = true,
	["Auto-Query Unknown Items"] = true,
	["Suppress Server Query Spam"] = true,
	["Compare Rewards and Gear (/rl)"] = true,
	["Dungeons"] = true,
	["Raids"] = true,
	["Entrances"] = true,
	["Transport Routes"] = true,
	["Showing all instances_1"] = true,
	["Showing all instances_2"] = true,
	["Type"] = true,
	["All"] = true,
	["No"] = true,
	["Instances level 15-29"] = true,
	["Instances level 30-39"] = true,
	["Instances level 40-49"] = true,
	["Instances level 50-59"] = true,
	["Instances 60 level"] = true,
	["Party Size"] = true,
	["Instances for 5 Players"] = true,
	["Instances for 10 Players"] = true,
	["Instances for 20 Players"] = true,
	["Instances for 40 Players"] = true,
	["Kalimdor Instances"] = true,
	["Eastern Kingdoms Instances"] = true,
	["Level"] = true,
	["Continent"] = true,
	["Location"] = true,
	["Level Range"] = true,
	["Player Limit"] = true,
	["Select Category"] = true,
	["Minimum Level"] = true,
	["Left-click to open Atlas-TW.\nMiddle-click for Atlas-TW options.\nRight-click and drag to move this button."] = true,
	["Instance"] = true,
	["Search Unavailable"] = true,
	["Not Available"] = true,
	["Quest finished:"] = true,
	["No Quests"] = true,
	[" Please click right until you see the Item frame."] = true,
	[" Try moving the cursor over the item in a second."] = true,
	["AtlasTWQuest is querying the server for: "] = true,
	["No Rewards"] = true,
	["This item is not safe!"] = true,
	["Item not found in cache"] = true,
	["Attain: "] = true,
	["Level: "] = true,
	["Requires"] = true,
	["Tools: "] = true,
	["Reagents: "] = true,
	["Starts at: \n"] = true,
	["Objective: \n"] = true,
	["Note: \n"] = true,
	["Prequest: "] = true,
	["Quest follows: "] = true,
	["Story"] = true,
	["Scale"] = true,
	["Show Loot Panel with AtlasTW"] = true,
	["Sort Instance by:"] = true,
	["Select Map"] = true,
	["Show Button on Minimap"] = true,
	["Auto-Select Instance Map"] = true,
	["Transparency"] = true,
	["Right-Click for World Map"] = true,
	["Show Acronyms"] = true,
	["Clamp window to screen"] = true,
	["Show Cursor Coordinates on Map"] = true,
	["Quests"] = true,
	["Quest"] = true,
	["East"] = true,
	["North"] = true,
	["South"] = true,
	["West"] = true,
	["Battlegrounds"] = true,
	["Lower"] = true,
	["Upper"] = true,
	["Entrance"] = true,
	["Exit"] = true,
	["Chase Begins"] = true,
	["Chase Ends"] = true,
	["Attunement Required"] = true,
	["Back"] = true,
	["Blacksmithing Plans"] = true,
	["Brazier of Invocation"] = true,
	["Connection"] = true,
	["Connections"] = true,
	["Damage: "] = true,
	["Tier 0.5 Summon"] = true,
	["Dungeon Locations"] = true,
	["Elevator"] = true,
	["Front"] = true,
	["Ghost"] = true,
	["Instances"] = true,
	["Key"] = true,
	["Key to Stormwrought Castle"] = true,
	["The Scepter of Medivh"] = true,
	["Upper Karazhan Tower Key"] = true,
	["Open Portal"] = true,
	["Meeting Stone"] = true,
	["Moonwell"] = true,
	["Neutral"] = true,
	["Optional"] = true,
	["Outside"] = true,
	["Portal"] = true,
	["Random"] = true,
	["Reputation"] = true,
	["Rescued"] = true,
	["Side"] = true,
	["Summon"] = true,
	["Teleport"] = true,
	["through "] = true,
	["Trash Mobs"] = true,
	["Unknown"] = true,
	["Varies"] = true,
	["Wanders"] = true,
	["Severs"] = true,
	["Need quest"] = true,

	--Instance names and acronyms
	["Armory"] = true,
	["Cathedral"] = true,
	["Graveyard"] = true,
	["Library"] = true,
	["Sunken Temple"] = true,


	--Set names
	["Set: "] = true,
	["Tier 0/0.5 Sets"] = true,
	["Zul'Gurub Sets"] = true,
	["Zul'Gurub Ring Sets"] = true,
	["Ruins of Ahn'Qiraj Sets"] = true,
	["Temple of Ahn'Qiraj Sets"] = true,
	["Tier 1 Sets"] = true,
	["Tier 2 Sets"] = true,
	["Tier 3 Sets"] = true,

	--************************************************
	-- Kalimdor Instance Data
	--************************************************

	--Ragefire Chasm
	["Maur Grimtotem"] = true,
	["Oggleflint"] = true,

	--Blackfathom Deeps
	["Lorgalis Manuscript"] = true,
	["Argent Guard Thaelrid"] = true,
	["Shrine of Gelihast"] = true,
	["Fathom Stone"] = true,
	["Morridune"] = true,
	["Altar of the Deeps"] = true,

	--Razorfen Kraul
	["Razorfen Spearhide"] = true,
	["Willix the Importer"] = true,
	["Heralath Fallowbrook"] = true,

	--Razorfen Downs
	["Henry Stern"] = true,
	["Belnistrasz"] = true,
	["Sah'rhee"] = true,

	--Zul'Farrak
	["Mallet of Zul'Farrak"] = true,
	["Theka the Martyr"] = true,
	["Zul'Farrak Dead Hero"] = true,
	["Nekrum Gutchewer"] = true,
	["Dustwraith"] = true,
	["Sergeant Bly"] = true,
	["Weegli Blastfuse"] = true,
	["Murta Grimgut"] = true,
	["Raven"] = true,
	["Oro Eyegouge"] = true,
	["Sandfury Executioner"] = true,
	["Hydromancer Velratha"] = true,
	["Elder Wildmane"] = true,
	["Zerillis"] = true,
	["Sandarr Dunereaver"] = true,

	--Maraudon	
	["Scepter of Celebras"] = true,
	["Veng"] = true,
	["Maraudos"] = true,
	["Elder Splitrock"] = true,

	--Dire Maul (East)
	["Old Ironbark"] = true,
	["A Dusty Tome"] = true,
	["Felvine Shard"] = true,
	["Dire Maul Books"] = true,

	--Dire Maul (North)
	["Crescent Key"] = true,
	["Gordok Courtyard Key"] = true,
	["Gordok Inner Door Key"] = true,
	--"Library" omitted from here and DM West because of SM: "Library" duplicate
	["Knot Thimblejack"] = true,
	["Tribute Run"] = true,

	--Dire Maul (West)
	["J'eevee's Jar"] = true,
	["Pylons"] = true,
	["Shen'dralar Ancient"] = true,
	["Ancient Equine Spirit"] = true,
	["Ferra"] = true,
	["Falrin Treeshaper"] = true,
	["Lorekeeper Lydros"] = true,
	["Lorekeeper Javon"] = true,
	["Lorekeeper Kildrath"] = true,
	["Lorekeeper Mykos"] = true,
	["Shen'dralar Provisioner"] = true,
	["Skeletal Remains of Kariel Winthalus"] = true,
	["The Prince's Chest"] = true,

	--Onyxia's Lair
	["Drakefire Amulet"] = true,
	["Onyxian Warders"] = true,
	["Whelp Eggs"] = true,

	--Temple of Ahn'Qiraj
	["Bug Trio"] = true,
	["Andorgos"] = true,
	["Vethsera"] = true,
	["Kandrostrasz"] = true,
	["Arygos"] = true,
	["Caelestrasz"] = true,
	["Merithra of the Dream"] = true,
	["AQ Enchants"] = true,
	["AQ Opening Quest Chain"] = true,

	--Ruins of Ahn'Qiraj
	["Four Kaldorei Elites"] = true,
	["Captain Qeez"] = true,
	["Captain Tuubid"] = true,
	["Captain Drenn"] = true,
	["Captain Xurrem"] = true,
	["Major Yeggeth"] = true,
	["Major Pakkon"] = true,
	["Colonel Zerran"] = true,
	["Safe Room"] = true,
	["Class Books"] = true,

	--****************************
	-- Eastern Kingdoms Instances
	--****************************
	--Dragonmaw Retreat
	["Pedestal of Unity"] = true,

	--Blackrock Depths
	["Shadowforge Key"] = true,
	["Prison Cell Key"] = true,
	["Jail Break!"] = true,
	["Banner of Provocation"] = true,
	["Kharan Mighthammer"] = true,
	["Commander Gor'shak"] = true,
	["Marshal Windsor"] = true,
	["Ring of Law"] = true,
	["Theldren"] = true,
	["Lefty"] = true,
	["Malgen Longspear"] = true,
	["Gnashjaw"] = true,
	["Korv"] = true,
	["Rezznik"] = true,
	["Rotfang"] = true,
	["Snokh Blackspine"] = true,
	["Va'jashni"] = true,
	["Volida"] = true,
	["Elder Morndeep"] = true,
	["High Justice Grimstone"] = true,
	["Monument of Franclorn Forgewright"] = true,
	["The Vault"] = true,
	["The Black Anvil"] = true,
	["Shadowforge Lock"] = true,
	["Field Repair Bot 74A"] = true,
	["The Grim Guzzler"] = true,
	["Lokhtos Darkbargainer"] = true,
	["Mistress Nagmara"] = true,
	["Plugger Spazzring"] = true,
	["Private Rocknot"] = true,
	["Summoner's Tomb"] = true,
	["Chest of The Seven"] = true,
	["The Lyceum"] = true,
	["High Priestess of Thaurissan"] = true,
	["The Black Forge"] = true,
	["Core Fragment"] = true,

	--Blackrock Spire (Lower)
	["Vaelan"] = true,
	["Warosh"] = true,
	["Elder Stonefort"] = true,
	["Roughshod Pike"] = true,
	["Spirestone Butcher"] = true,
	["Spirestone Battle Lord"] = true,
	["Spirestone Lord Magus"] = true,
	["Fifth Mosh'aru Tablet"] = true,
	["Bijou"] = true,
	["Sixth Mosh'aru Tablet"] = true,
	["Bijou's Belongings"] = true,
	["Human Remains"] = true,
	["Unfired Plate Gauntlets"] = true,
	["Urok's Tribute Pile"] = true,
	["Burning Felguard"] = true,

	--Blackrock Spire (Upper)
	["Seal of Ascension"] = true,
	["Father Flame"] = true,
	["Darkstone Tablet"] = true,
	["Doomrigger's Coffer"] = true,
	["Awbee"] = true,
	["Finkle Einhorn"] = true,
	["Drakkisath's Brand"] = true,

	--Blackwing Lair
	["Draconic for Dummies"] = true,
	["Master Elemental Shaper Krixix"] = true,
	["Alchemy Lab"] = true,

	--Gnomeregan
	["Workshop Key"] = true,
	["Blastmaster Emi Shortfuse"] = true,
	["Clean Room"] = true,
	["Tink Sprocketwhistle"] = true,
	["The Sparklematic 5200"] = true,
	["Mail Box"] = true,
	["Kernobee"] = true,
	["Alarm-a-bomb 2600"] = true,
	["Matrix Punchograph 3005-B"] = true,
	["Matrix Punchograph 3005-C"] = true,
	["Matrix Punchograph 3005-D"] = true,

	--Molten Core
	["Aqual Quintessence"] = true,
	["Eternal Quintessence"] = true,
	["Random Boss Loot"] = true,

	--Naxxramas
	["Archmage Tarsis Kir-Moldir"] = true,
	["Mr. Bigglesworth"] = true,
	["Abomination Wing"] = true,
	["Spider Wing"] = true,
	["Deathknight Wing"] = true,
	["Plague Wing"] = true,
	["Frostwyrm Lair"] = true,
	["Icebellow Anvil"] = true,

	--SM: Library
	["Doan's Strongbox"] = true,

	--SM: Armory
	["The Scarlet Key"] = true,--omitted from SM: Cathedral

	--SM: Graveyard
	["Vorrel Sengutz"] = true,

	--Scholomance
	["Skeleton Key"] = true,
	["Viewing Room Key"] = true,
	["Viewing Room"] = true,
	["Blood of Innocents"] = true,
	["Divination Scryer"] = true,
	["Blood Steward of Kirtonos"] = true,
	["The Deed to Southshore"] = true,
	["Journal of Jandice Barov"] = true,
	["The Deed to Tarren Mill"] = true,
	["The Deed to Brill"] = true,
	["The Deed to Caer Darrow"] = true,
	["Torch Lever"] = true,
	["Old Treasure Chest"] = true,

	--Shadowfang Keep
	["Sorcerer Ashcrombe"] = true,
	["Deathstalker Adamant"] = true,
	["Deathstalker Vincent"] = true,
	["Fel Steed"] = true,
	["Jordan's Hammer"] = true,
	["The Book of Ur"] = true,

	--Stratholme
	["Key to the City"] = true,
	["Various Postbox Keys"] = true,
	["Living Side"] = true,
	["Undead Side"] = true,
	["Stratholme Courier"] = true,
	["Fras Siabi"] = true,
	["Atiesh"] = true,
	["Elder Farwhisper"] = true,
	["Malor's Strongbox"] = true,
	["Crimson Hammersmith"] = true,
	["Grand Crusader Dathrohan"] = true,
	["Aurius"] = true,
	["Black Guard Swordsmith"] = true,
	["Ysida Harmon"] = true,
	["Crusaders' Square Postbox"] = true,
	["Market Row Postbox"] = true,
	["Festival Lane Postbox"] = true,
	["Elders' Square Postbox"] = true,
	["King's Square Postbox"] = true,
	["Fras Siabi's Postbox"] = true,
	["Third Postbox Opened"] = true,

	--The Deadmines
	["Sneed's Shredder"] = true,
	["Defias Gunpowder"] = true,

	--The Sunken Temple
	["Yeh'kinya's Scroll"] = true,
	["Balcony Minibosses"] = true,
	["Altar of Hakkar"] = true,
	["Essence Font"] = true,
	["Spawn of Hakkar"] = true,
	["Elder Starsong"] = true,
	["Statue Activation Order"] = true,
	["Malfurion Stormrage"] = true,

	--Uldaman
	["Staff of Prehistoria"] = true,
	["Baelog's Chest"] = true,
	["Conspicuous Urn"] = true,
	["Remains of a Paladin"] = true,
	["Annora"] = true,
	["Tablet of Will"] = true,
	["Shadowforge Cache"] = true,
	["The Discs of Norgannon"] = true,
	["Ancient Treasure"] = true,

	--Zul'Gurub
	["Mudskunk Lure"] = true,
	["Gurubashi Mojo Madness"] = true,
	["Zanza the Restless"] = true,
	["Ohgan"] = true,
	["Edge of Madness"] = true,
	["Zealot Zath"] = true,
	["Zealot Lor'Khan"] = true,
	["Muddy Churning Waters"] = true,
	["Jinxed Hoodoo Pile"] = true,
	["ZG Enchants"] = true,

	--************************************************
	-- Instance Entrance Maps
	--************************************************

	--Blackrock Mountain (Entrance)
	["Bodley"] = true,
	["Orb of Command"] = true,

	--Gnomeregan (Entrance)
	["Transpolyporter"] = true,
	["Matrix Punchograph 3005-A"] = true,

	--Maraudon (Entrance)
	["The Nameless Prophet"] = true,

	--The Deadmines (Entrance)

	--Sunken Temple (Entrance)
	["Jade"] = true,

	--Uldaman (Entrance)
	["Tablet of Ryun'Eh"] = true,
	["Krom Stoutarm's Chest"] = true,
	["Garrett Family Chest"] = true,
	["Digmaster Shovelphlange"] = true,

	--Wailing Caverns (Entrance)
	["Above the Entrance:"] = true,
	["Nalpak"] = true,
	["Kalldan Felmoon"] = true,
	["Waldor"] = true,

	--Dire Maul (Entrance)
	["Dire Pool"] = true,
	["Dire Maul Arena"] = true,
	["Mushgog"] = true,
	["Skarr the Unbreakable"] = true,
	["The Razza"] = true,
	["Elder Mistwalker"] = true,
	["Griniblix the Spectator"] = true,

	--World
	["Emerald Dragons"] = true,
	["Spirit of Azuregos"] = true,
	["Emerald Dragons Trash"] = true,
	["Nethergarde Keep"] = true,

	--Battlegrounds

	--Places
	["Friendly Reputation Rewards"] = true,
	["Honored Reputation Rewards"] = true,
	["Revered Reputation Rewards"] = true,
	["Exalted Reputation Rewards"] = true,

	--Alterac Valley (North)
	["Stormpike Guard"] = true,
	["Dun Baldar"] = true,
	["Vanndar Stormpike"] = true,
	["Dun Baldar North Marshal"] = true,
	["Dun Baldar South Marshal"] = true,
	["Icewing Marshal"] = true,
	["Iceblood Marshal"] = true,
	["Stonehearth Marshal"] = true,
	["East Frostwolf Marshal"] = true,
	["West Frostwolf Marshal"] = true,
	["Tower Point Marshal"] = true,
	["Prospector Stonehewer"] = true,
	["Irondeep Mine"] = true,
	["Morloch"] = true,
	["Umi Thorson"] = true,
	["Keetar"] = true,
	["Arch Druid Renferal"] = true,
	["Dun Baldar North Bunker"] = true,
	["Wing Commander Mulverick"] = true,
	["Murgot Deepforge"] = true,
	["Dirk Swindle"] = true,
	["Athramanis"] = true,
	["Lana Thunderbrew"] = true,
	["Stormpike Aid Station"] = true,
	["Stormpike Stable Master"] = true,
	["Stormpike Ram Rider Commander"] = true,
	["Svalbrad Farmountain"] = true,
	["Kurdrum Barleybeard"] = true,
	["Stormpike Quartermaster"] = true,
	["Jonivera Farmountain"] = true,
	["Brogus Thunderbrew"] = true,
	["Wing Commander Ichman"] = true,
	["Wing Commander Slidore"] = true,
	["Wing Commander Vipore"] = true,
	["Dun Baldar South Bunker"] = true,
	["Corporal Noreg Stormpike"] = true,
	["Gaelden Hammersmith"] = true,
	["Stormpike Graveyard"] = true,
	["Icewing Cavern"] = true,
	["Stormpike Banner"] = true,
	["Stormpike Lumber Yard"] = true,
	["Wing Commander Jeztor"] = true,
	["Icewing Bunker"] = true,
	["Wing Commander Guse"] = true,
	["Stonehearth Graveyard"] = true,
	["Stonehearth Outpost"] = true,
	["Captain Balinda Stonehearth"] = true,
	["Snowfall Graveyard"] = true,
	["Korrak the Bloodrager"] = true,
	["Ichman's Beacon"] = true,
	["Mulverick's Beacon"] = true,
	["Stonehearth Bunker"] = true,
	["Ivus the Forest Lord"] = true,
	["Western Crater"] = true,
	["Vipore's Beacon"] = true,
	["Jeztor's Beacon"] = true,
	["Eastern Crater"] = true,
	["Slidore's Beacon"] = true,
	["Guse's Beacon"] = true,
	["Graveyards, Capturable Areas"] = true,
	["Bunkers, Towers, Destroyable Areas"] = true,
	["Assault NPCs, Quest Areas"] = true,
	["Steamsaw"] = true,

	--Alterac Valley (South)
	["Frostwolf Clan"] = true,
	["Frostwolf Keep"] = true,
	["Drek'Thar"] = true,
	["Duros"] = true,
	["Drakan"] = true,
	["West Frostwolf Warmaster"] = true,
	["East Frostwolf Warmaster"] = true,
	["Tower Point Warmaster"] = true,
	["Iceblood Warmaster"] = true,
	["Icewing Warmaster"] = true,
	["Stonehearth Warmaster"] = true,
	["Dun Baldar North Warmaster"] = true,
	["Dun Baldar South Warmaster"] = true,
	["Lokholar the Ice Lord"] = true,
	["Iceblood Garrison"] = true,
	["Captain Galvangar"] = true,
	["Iceblood Tower"] = true,
	["Iceblood Graveyard"] = true,
	["Tower Point"] = true,
	["Coldtooth Mine"] = true,
	["Taskmaster Snivvle"] = true,
	["Masha Swiftcut"] = true,
	["Aggi Rumblestomp"] = true,
	["Frostwolf Graveyard"] = true,
	["Jotek"] = true,
	["Smith Regzar"] = true,
	["Primalist Thurloga"] = true,
	["Sergeant Yazra Bloodsnarl"] = true,
	["Frostwolf Stable Master"] = true,
	["Frostwolf Wolf Rider Commander"] = true,
	["Frostwolf Quartermaster"] = true,
	["West Frostwolf Tower"] = true,
	["East Frostwolf Tower"] = true,
	["Frostwolf Relief Hut"] = true,
	["Wildpaw Cavern"] = true,
	["Frostwolf Banner"] = true,

	--Arathi Basin
	["The Defilers"] = true,
	["The League of Arathor"] = true,
	["Trollbane Hall"] = true,
	["Defiler's Den"] = true,
	["Stables"] = true,
	["Gold Mine"] = true,
	["Blacksmith"] = true,
	["Lumber Mill"] = true,
	["Farm"] = true,

	--Warsong Gulch
	["Warsong Outriders"] = true,
	["Silverwing Sentinels"] = true,
	["Silverwing Hold"] = true,
	["Warsong Lumber Mill"] = true,

	--Flight points
	["Flight Path Maps"] = true,
	["Druid-only"] = true,
	["Aerie Peak"] = true,
	["Azeroth"] = true,
	["Astranaar"] = true,
	["Auberdine"] = true,
	["Bloodvenom Post"] = true,
	["Booty Bay"] = true,
	["Brackenwall Village"] = true,
	["Camp Mojache"] = true,
	["Camp Taurajo"] = true,
	["Cenarion Hold"] = true,
	["Chillwind Point"] = true,
	["Crossroads"] = true,
	["Darkshire"] = true,
	["Everlook"] = true,
	["Feathermoon Stronghold"] = true,
	["Mudsprocket"] = true,
	["Nordanaar"] = true,
	["Alah'Thalas"] = true,
	["Dun Agrath"] = true,
	["Ravenshire"] = true,
	["Ironforge Airfields"] = true,
	["Caelan's Rest"] = true,
	["Bael Hardul"] = true,
	["Flame Crest"] = true,
	["Freewind Post"] = true,
	["Tel Co. Basecamp"] = true,
	["Stillward Church"] = true,
	["Hammerfall"] = true,
	["Kargath"] = true,
	["Lakeshire"] = true,
	["Light's Hope Chapel"] = true,
	["Marshal's Refuge"] = true,
	["Menethil Harbor"] = true,
	["Morgan's Vigil"] = true,
	["Nighthaven"] = true,
	["Nijel's Point"] = true,
	["Ratchet"] = true,
	["Refuge Pointe"] = true,
	["Revantusk Village"] = true,
	["Rut'Theran Village"] = true,
	["Sentinel Hill"] = true,
	["Shadowprey Village"] = true,
	["Southshore"] = true,
	["Splintertree Post"] = true,
	["Stonard"] = true,
	["Stonetalon Peak"] = true,
	["Sun Rock Retreat"] = true,
	["Talonbranch Glade"] = true,
	["Talrendis Point"] = true,
	["Tarren Mill"] = true,
	["Thalanaar"] = true,
	["The Sepulcher"] = true,
	["Thelsamar"] = true,
	["Theramore Isle"] = true,
	["Thorium Point"] = true,
	["Valormok"] = true,
	["Zoram'gar Outpost"] = true,
	["South of the path along Lake Elune'ara"] = true,
	["West of the path to Timbermaw Hold"] = true,
	["Kalanar's Strongbox"] = true,
	["Caverns of Time"] = true,
	["Arc'tiras / Vault Armory Equipment"] = true,
	["Manuscript of Hydromancy II"] = true,
	["Harlow Family Chest"] = true,
	["Dawnstone Plans"] = true,
	["Greymane Armor"] = true,
	["Engraved Golden Bracelet"] = true,
	["Comfortable Pillow"] = true,
	["Councilman Kyleson"] = true,
	["Lord Ebonlocke"] = true,
	["Obsidian Rod"] = true,
	["Duke Rothlen"] = true,
	["Lower Karazhan Halls Enchants"] = true,
	["Tower of Karazhan Sets"] = true,
	["Incendosaur Skin Armor"] = true,
	["Favor of Erennius (ES Hard Mode)"] = true,
	["Hateforge Chemistry Documents"] = true,
	["Tome of Arcane Intricacies and Magical Phenomenon IX"] = true,
	["Sunnyglade Valley"] = true,
	["Sparkwater Port"] = true,
	["Maul'ogg Refuge"] = true,
	["Gnomeregan Reclamation Facility"] = true,
	--1.18
	["Flame of Farrak"] = true,
	["Steepcliff Port"] = true,
	["Shatterblade Post"] = true,
	["Dun Kithas"] = true,
	["Slickwick Oil Rig"] = true,
	["SI:7 Outpost"] = true,
	["Ambershire"] = true,
	["Stormbreaker Point"] = true,

	--AtlasTWLoot
	["AtlasTWLoot"] = true,
	["AtlasTW"] = true,
	["No match found for"] = true,
	["Search"] = true,
	["Clear"] = true,
	["Select Loot Table"] = true,
	["Select Sub-Table"] = true,
	["Drop Rate: "] = true,
	["Various Locations"] = true,
	["NoticeText"] = "|cff9D2C2CIf you find anything missing, please report it at:|r",
	["NoticeLink"]= "|cff9D2C2Chttps://github.com/byCFM2/Atlas-TW/issues/|r",
	["Link"]= "|cff9D2C2Chttps://github.com/byCFM2/Atlas-TW/|r",
	-- Version check / update messages
	["|cffff2020Update available|r"] = true,
	["Version: %s"] = true,
	["Version check sent to %s"] = true,
	["NewVersionAvailableFmt"] = "Atlas-TW: |cffff0000New version available!|r |cff00ff00Download here:|r %s",
	[" |cffA52A2Aloaded."] = true,
	[" is safe."] = true,
	["Server queried for "] = true,
	[". Right click on any other item to refresh the loot page."] = true,
	["Level 60"] = true,
	["Misc"] = true,
	["Skill:"] = true,
	["QuickLook"] = true,
	["Add to QuickLooks"] = true,
	["Assign this loot table to QuickLook"] = true,
	["Dungeons & Raids"] = true,
	["Button Position"] = true,
	["Button Radius"] = true,
	["Reset Position"] = true,
	["has been reset!"] = true,
	["|cff9d9d9dALT+Click to clear|r"] = true,
	["ALT+Click on item to add or remove it from WishList"] = true,
	["Safe Chat Links |cff1eff00(recommended)|r"] = true,
	["Enable all Chat Links"] = true,
	["Default Tooltips"] = true,
	["Lootlink Tooltips"] = true,
	["|cff9d9d9dLootlink Tooltips|r"] = true,
	["ItemSync Tooltips"] = true,
	["|cff9d9d9dItemSync Tooltips|r"] = true,
	["Use EquipCompare"] = true,
	["|cff9d9d9dUse EquipCompare|r"] = true,
	["Make Loot Table Opaque"] = true,
	["Show IDs at all times"] = true,
	["Suppress Text Spam"] = true,
	["Done"] = true,
	["Loot Panel"] = true,
	["Loot"] = true,
	["WishList"] = true,
	["Search Result: %s"] = true,
	["Search Result"] = true,
	["Last Result"] = true,
	["Search options"] = true,
	["Partial matching"] = true,
	["If checked, AtlasTWLoot searches item names for a partial match."] = true,
	["Default settings applied!"] = true,
	["Reset Settings"] = true,
	["AtlasTWLoot Error!"] = true,
	["To cast "] = true,
	[" the following items are needed:"] = true,
	[" you need this: "] = true,
	["To craft "] = true,
	[" the following reagents are needed:"] = true,
	[" added to the WishList."] = true,
	[" already in the WishList!"] = true,
	[" deleted from the WishList."] = true,
	[" not found in the WishList."] = true,
	["Options"] = true,
	["Collections"] = true,
	["Factions"] = true,
	["World Events"] = true,
	["Crafting"] = true,
	["Sets"] = true,
	["Priest Sets"] = true,
	["Mage Sets"] = true,
	["Warlock Sets"] = true,
	["Rogue Sets"] = true,
	["Druid Sets"] = true,
	["Hunter Sets"] = true,
	["Shaman Sets"] = true,
	["Paladin Sets"] = true,
	["Warrior Sets"] = true,
	["Crafted Sets - Blacksmithing"] = true,
	["Crafted Sets - Tailoring"] = true,
	["Crafted Sets - Leatherworking"] = true,
	["Setup"] = true,
	["Professions"] = true,
	["ItemID:"] = true,
	["SpellID:"] = true,
	["You can right-click to attempt to query the server."] = true,
	["Mount"] = true,
	["Glyph"] = true,
	["Enchant"] = true,
	["Trade Goods"] = true,
	["Scope"] = true,
	["Book"] = true,
	["Banner"] = true,
	["Set"] = true,
	["Token"] = true,
	["Token Hand-Ins"] = true,
	["Fireworks"] = true,
	["Cloak"] = true,
	["Weapon"] = true,
	["Weapons"] = true,
	["Classes"] = true,
	["This Item Begins a Quest"] = true,
	["Quest Item"] = true,
	["Quest Reward"] = true,
	["Shared"] = true,
	["Unique"] = true,
	["Right Half"] = true,
	["Left Half"] = true,
	["Vendor"] = true,
	["Pickpocketed"] = true,
	["Slot"] = true,
	["Prizes"] = true,
	["Decks"] = true,
	["28 Slot Bag"] = true,
	["18 Slot Bag"] = true,
	["10 Slot Bag"] = true,
	["24 Slot"] = true,
	["16 Slot"] = true,
	["Schematic: Field Repair Bot 74A"] = true,
	["Container"] = true,
	["Consumable"] = true,
	["Needed to purchase rewards"] = true,
	["Use to purchase rewards"] = true,
	["World"] = true,
	["Rare Mobs"] = true,
	["Tier 1"] = true,
	["Tier 2"] = true,
	["Tier 3"] = true,
	["Used to summon boss"] = true,
	["Coin"] = true,
	["Doll"] = true,
	["Water"] = true,
	["Earth"] = true,
	["Air"] = true,
	["Warpwood Pod"] = true,
	["Scarab Coffer"] = true,
	["Greater Scarab Coffer"] = true,
	["Master Angler"] = true,
	["First Prize"] = true,
	["Rare Fish Rewards"] = true,
	["Rare Fish"] = true,
	["Companion"] = true,
	["Arena Spoils"] = true,
	["Random stats"] = true,
	["Random resistance"] = true,
	["Random color"] = true,
	["Toy"] = true,
	["Cache"] = true,
	["Path of the Conqueror"] = true,
	["Path of the Invoker"] = true,
	["Path of the Protector"] = true,
	["Scourge Invasion Bosses"] = true,
	["Primal Hakkari Kossack"] = true,
	["Primal Hakkari Shawl"] = true,
	["Primal Hakkari Bindings"] = true,
	["Primal Hakkari Sash"] = true,
	["Primal Hakkari Stanchion"] = true,
	["Primal Hakkari Aegis"] = true,
	["Primal Hakkari Girdle"] = true,
	["Primal Hakkari Armsplint"] = true,
	["Primal Hakkari Tabard"] = true,
	["Qiraji Ornate Hilt"] = true,
	["Qiraji Martial Drape"] = true,
	["Qiraji Magisterial Ring"] = true,
	["Qiraji Ceremonial Ring"] = true,
	["Qiraji Regal Drape"] = true,
	["Qiraji Spiked Hilt"] = true,
	["Qiraji Bindings of Dominance"] = true,
	["Qiraji Bindings of Command"] = true,
	["Vek'nilash's Circlet"] = true,
	["Vek'lor's Diadem"] = true,
	["Ouro's Intact Hide"] = true,
	["Skin of the Great Sandworm"] = true,
	["Husk of the Old God"] = true,
	["Carapace of the Old God"] = true,
	["Zul'Gurub Rings"] = true,
	["The Twin Blades of Hakkari"] = true,
	["Primal Blessing"] = true,
	["AQ40 Class Sets"] = true,
	["AQ20 Class Sets"] = true,
	["Pre 60 Sets"] = true,
	["Crafted Sets"] = true,
	["Crafted Epic Weapons"] = true,
	["AQ20"] = true,
	["AQ40"] = true,
	["Zul'Gurub Class Sets"] = true,
	["Shared Zul'Gurub Priest Drops"] = true,
	["Enchants"] = true,
	["Tier 0.5"] = true,
	["Tier 0.5 Summonable"] = true,
	["Dungeon Sets"] = true,
	["PvP Sets"] = true,
	["PvP Accessories - Alliance"] = true,
	["PvP Accessories - Horde"] = true,
	["PvP Rewards"] = true,
	["PvP Armor Sets"] = true,
	["PvP Weapons"] = true,
	["PvP Accessories"] = true,
	["Collector's Edition"] = true,
	["Plans: Serenity"] = true,
	["Plans: Corruption"] = true,
	["Epic Set"] = true,
	["Rare Set"] = true,
	["Legendary Items"] = true,
	["Charges"] = true,
	["Artifact Items"] = true,
	["Fire Resistance Gear"] = true,
	["Arcane Resistance Gear"] = true,
	["Nature Resistance Gear"] = true,
	["Rare Pets"] = true,
	["Rare Mounts"] = true,
	["Old Mounts"] = true,
	["PvP Mounts"] = true,
	["Tabards"] = true,
	["<Random enchantment>"] = true,
	["World Epics"] = true,
	["World Blues"] = true,
	["Druid of the Fang"] = true,
	["Defias Strip Miner"] = true,
	["Defias Pirate"] = true,
	["Prisoner/Insurgent/Convict"] = true,
	["Defender"] = true,
	["Protector"] = true,
	["Myrmidon"] = true,
	["Champion"] = true,
	["Centurion"] = true,
	["Guardsman"] = true,
	["Scarlet Trainee"] = true,
	["Plagued Hatchling"] = true,
	["Shadowforge Flame Keeper"] = true,
	["Hammered Patron"] = true,
	["Scarshield Warlock"] = true,
	["Crimson Sorcerer"] = true,
	["Thuzadin Shadowcaster"] = true,
	["Crimson Inquisitor"] = true,
	["Crimson Battle Mage"] = true,
	["Ghoul Ravener"] = true,
	["Spectral Citizen"] = true,
	["Spectral Researcher"] = true,
	["Scholomance Adept"] = true,
	["Scholomance Dark Summoner"] = true,
	["Twilight Corrupter"] = true,
	["Blackhand Elite"] = true,
	["Blackhand Assassin"] = true,
	["Firebrand Pyromancer"] = true,
	["Firebrand Invoker"] = true,
	["Firebrand Grunt"] = true,
	["Firebrand Legionnaire"] = true,
	["Death Talon Wyrmguard"] = true,
	["Dark Iron Agent"] = true,
	["Molten Destroyer"] = true,
	["Spire Spider/Spiderling"] = true,
	["Spirestone Warlord"] = true,
	["Spirestone Mystic"] = true,
	["Anvilrage Captain"] = true,
	["Anvilrage Marshal"] = true,
	["Doomforge Arcanasmith"] = true,
	["Weapon Technician"] = true,
	["Doomforge Craftsman"] = true,
	["Murk Worm"] = true,
	["Atal'ai Witch Doctor"] = true,
	["Crimson Templar"] = true,
	["Azure Templar"] = true,
	["Hoary Templar"] = true,
	["Earthen Templar"] = true,
	["The Duke of Cynders"] = true,
	["The Duke of Fathoms"] = true,
	["The Duke of Zephyrs"] = true,
	["The Duke of Shards"] = true,
	["Templars"] = true,
	["Dukes"] = true,
	["High Council"] = true,
	["The Nameles Prophet"] = true,
	["Rajaxx's Captains"] = true,
	["Dark Coffer"] = true,
	["Fengus's Chest"] = true,
	["Unforged Rune Covered Breastplate"] = true,
	["Malor the Zealous"] = true,
	["Gift of Adoration"] = true,
	["Box of Chocolates"] = true,
	["Treat Bag"] = true,
	["Gaily Wrapped Present"] = true,
	["Festive Gift"] = true,
	["Gently Shaken Gift"] = true,
	["Brightly Colored Egg"] = true,
	["Tribute Chest"] = true,
	["Abyssal Council"] = true,
	["Children's Week"] = true,
	["Elemental Invasion"] = true,
	["Feast of Winter Veil"] = true,
	["Gurubashi Arena"] = true,
	["Harvest Festival"] = true,
	["Love is in the Air"] = true,
	["Midsummer Fire Festival"] = true,
	["Noblegarden"] = true,
	["Stranglethorn Fishing Extravaganza"] = true,
	["Keys"] = true,
	["Half-Buried Treasure Chest"] = true,
	["Princess Tempestria"] = true,
	["Apprentice"] = true,
	["Journeyman"] = true,
	["Expert"] = true,
	["Artisan"] = true,
	["Master Axesmith"] = true,
	["Master Hammersmith"] = true,
	["Master Swordsmith"] = true,
	["Gnomish Engineering"] = true,
	["Goblin Engineering"] = true,
	["Relic Coffer"] = true,
	["Secret Safe"] = true,
	["Dark Keeper"] = true,
	["LW"] = true,
	["Druid"] = true,
	["Hunter"] = true,
	["Mage"] = true,
	["Paladin"] = true,
	["Priest"] = true,
	["Rogue"] = true,
	["Shaman"] = true,
	["Warlock"] = true,
	["Warrior"] = true,
	["Head"] = true,
	["Neck"] = true,
	["Shoulder"] = true,
	["Chest"] = true,
	["Shirt"] = true,
	["Tabard"] = true,
	["Wrist"] = true,
	["Hands"] = true,
	["Waist"] = true,
	["Legs"] = true,
	["Feet"] = true,
	["Ring"] = true,
	["Finger"] = true,
	["Trinket"] = true,
	["Held In Off-hand"] = true,
	["Relic"] = true,
	["Relics"] = true,
	["One-Hand"] = true,
	["Two-Hand"] = true,
	["Main Hand"] = true,
	["Off Hand"] = true,
	["Ranged"] = true,
	["Axe"] = true,
	["Bow"] = true,
	["Crossbow"] = true,
	["Dagger"] = true,
	["Gun"] = true,
	["Mace"] = true,
	["Polearm"] = true,
	["Shield"] = true,
	["Staff"] = true,
	["Sword"] = true,
	["Thrown"] = true,
	["Wand"] = true,
	["Fist Weapon"] = true,
	["Idol"] = true,
	["Totem"] = true,
	["Libram"] = true,
	["Arrow"] = true,
	["Bullet"] = true,
	["Quiver"] = true,
	["Ammo Pouch"] = true,
	["Bag"] = true,
	["Potion"] = true,
	["Food"] = true,
	["Drink"] = true,
	["Bandage"] = true,
	["Reagent"] = true,
	["Binds when picked up"] = true,
	["Darkmoon Faire Card"] = true,
	["Fishing Pole"] = true,
	["Kara40"] = true,
	["Turtlhu, the Black Turtle of Doom"] = true,
	["Blood Ring Friendly Rewards"] = true,
	["Blood Ring Honored Rewards"] = true,
	["Blood Ring Revered Rewards"] = true,
	["Blood Ring Exalted Rewards"] = true,
	["AB 20-29 Honored Rewards"] = true,
	["AB 30-39 Honored Rewards"] = true,
	["AB 40-49 Honored Rewards"] = true,
	["AB 50-59 Honored Rewards"] = true,
	["AB 20-29 Revered Rewards"] = true,
	["AB 30-39 Revered Rewards"] = true,
	["AB 40-49 Revered Rewards"] = true,
	["AB 50-59 Revered Rewards"] = true,
	["AB Exalted Rewards"] = true,
	["AV Friendly Rewards"] = true,
	["AV Honored Rewards"] = true,
	["AV Revered Rewards"] = true,
	["AV Exalted Rewards"] = true,
	["Gemstones"] = true,
	["Token of Blood Rewards"] = true,
	["Friendly Rewards"] = true,
	["Honored Rewards"] = true,
	["Revered Rewards"] = true,
	["Exalted Rewards"] = true,
	["PvP Trinkets"] = true,
	["Cooking Fire"] = true,
	["Anvil"] = true,
	["Black Anvil"] = true,
	["Forge"] = true,
	["Black Forge"] = true,
	["Smokywood Pastures Special Gift"] = true,
	["Smokywood Pastures"] = true,
	["Rank"] = true,
	["Projectile"] = true,
	["Polearms"] = true,
	["Staves"] = true,
	["Bows"] = true,
	["Crossbows"] = true,
	["Guns"] = true,
	["Shields"] = true,
	["Wands"] = true,
	["Rings"] = true,
	["Ivus & Lokholar"] = true,
	["Tablet of Ryun'eh"] = true,
	["Gloves"] = true,
	["Boots"] = true,
	["2H Weapon"] = true,
	["Flasks"] = true,
	["Protection Potions"] = true,
	["Healing and Mana Potions"] = true,
	["Transmutes"] = true,
	["Transmogrification"] = true,
	["Defensive Potions and Elixirs"] = true,
	["Offensive Potions and Elixirs"] = true,
	["Miscellaneous"] = true,
	["Helm"] = true,
	["Shoulders"] = true,
	["Bracers"] = true,
	["Belt"] = true,
	["Pants"] = true,
	["Bags"] = true,
	["Axes"] = true,
	["Swords"] = true,
	["Maces"] = true,
	["Fist"] = true,
	["Belt Buckles"] = true,
	["Equipment"] = true,
	["Trinkets"] = true,
	["Explosives"] = true,
	["Parts"] = true,
	["Amulets"] = true,
	["Show Source on Tooltips"] = true,
	["Off-hand"] = true,
	["Overseer Taskmaster"] = true,
	["Kara40 Sets"] = "Tower of Karazhan Sets",
	["High Marshal Whirlaxis"] = true,
	["Baron Kazum"] = true,
	["Prince Skaldrenox"] = true,
	["Lord Skwol"] = true,
	["(Graveyard)"] = true,
	["(Armory)"] = true,
	["(Cathedral)"] = true,
	["(Library)"] = true,
	["(West)"] = true,
	["(East)"] = true,
	["(North)"] = true,
	["Earthcaller Rezengal"] = true,
	["Graypaw Alpha"] = true,
	["Shade Mage"] = true,
	["Blazespark"] = true,
	["Friar Montero"] = true,
	["Emastrasz"] = true,
	["Gnaws"] = true,
	["Witch Doctor Tan'zo"] = true,
	["Widow of the Woods"] = true,
	["Dawnhowl"] = true,
	["Maltimor's Prototype"] = true,
	["Bonecruncher"] = true,
	["Duskskitterer"] = true,
	["Baron Perenolde"] = true,
	["Kin'Tozo"] = true,
	["Grug'thok the Seer"] = true,
	["M-0L1Y"] = true,
	["Explorer Ashbeard"] = true,
	["Jal'akar"] = true,
	["Embereye"] = true,
	["Ruk'thok the Pyromancer"] = true,
	["Tarangos"] = true,
	["Ripjaw"] = true,
	["Xalvic Blackclaw"] = true,
	["Aquitus"] = true,
	["Firstborn of Arugal"] = true,
	["Letashaz"] = true,
	["Margon the Mighty"] = true,
	["The Wandering Knight"] = true,
	["Stoneshell"] = true,
	["Zareth Terrorblade"] = true,
	["Highvale Silverback"] = true,
	["Mallon The Moontouched"] = true,
	["Blademaster Kargron"] = true,
	["Professor Lysander"] = true,
	["Admiral Barean Westwind"] = true,
	["Azurebeak"] = true,
	["Barkskin Fisher"] = true,
	["Crusader Larsarius"] = true,
	["Shadeflayer Goliath"] = true,
	["Nature, Fire, Arcane, Shadow, Frost"] = true,
	["Ironspine"] = true,
	["Nature, Shadow"] = true,
	["Karazhan Crypt Key"] = true,
	["Mini Bosses"] = true,
	["Previous"] = true,
	["Next"] = true,
	["Level One Lunatic Challenge"] = true,
	["Snowball"] = true,
	["Drifting Avatar of Time"]	= true,
}